<?php
/**
* Biblioteca para importar gettext de arquivos PO.
* PHP ^8.0
*
* @package		ronnyjss\traducao
* @author		Ronny Santos <ronny@jss.art.br>
* @copyright	© 2021 RonnyJSS
* @license		AGPL-3.0
* @link			github.com/ronnyjss/traducao
**/

namespace ronnyjss\traducao;

# Lista de linguagens utilizadas em servudir Linux/Windows.
# https://www.gnu.org/software/gettext/manual/html_node/Usual-Language-Codes.html#Usual-Language-Codes
# https://www.gnu.org/software/gettext/manual/html_node/Country-Codes.html#Country-Codes
const LINGUAGENS = [
	'af_ZA' => 'Afrikaans_South Africa',	# Afrikaans						# Afrikaans
	'sq_AL' => 'Albanian_Albania',			# Albanês
	'ar_DZ' => 'Arabic_Algeria',			# Árabe (Argélia)
	'ar_BH' => 'Arabic_Bahrain',			# Árabe (Bahrein)
	'ar_EG' => 'Arabic_Egypt',				# Árabe (Egito)
	'ar_IQ' => 'Arabic_Iraq',				# Árabe (Iraque)
	'ar_JO' => 'Arabic_Jordan',				# Árabe (Jordânia)
	'ar_KW' => 'Arabic_Kuwait',				# Árabe (Kuwait)
	'ar_LB' => 'Arabic_Lebanon',			# Árabe (Líbano)
	'ar_LY' => 'Arabic_Libya',				# Árabe (Líbia)
	'ar_MA' => 'Arabic_Morocco',			# Árabe (Marrocos)
	'ar_OM' => 'Arabic_Oman',				# Árabe (Omã)
	'ar_QA' => 'Arabic_Qatar',				# Árabe (Catar)
	'ar_SA' => 'Arabic_Saudi_Arabia',		# Árabe (Arábia Saudita)
	'ar_SD' => 'Arabic_Sudan',				# Árabe (Sudão)
	'ar_SY' => 'Arabic_Syria',				# Árabe (Síria)
	'ar_TN' => 'Arabic_Tunisia',			# Árabe (Tunísia)
	'ar_AE' => 'Arabic_UAE',				# Árabe (Emirados Árabes Unidos)
	'ar_YE' => 'Arabic_Yemen',				# Árabe (Iémen)
	'eu_ES' => 'Basque_Spain',				# Basco (Espanha)
	'be_BY' => 'Belarusian_Belarus',		# Bielorusso (Bielorrússia)
	'bg_BG' => 'Bulgarian_Bulgaria',		# Búlgaro (Bulgária)
	'ca_ES' => 'Catalan_Spain',				# Catalão (Espanha)
	'zh_TW' => 'Chinese_Taiwan',			# Chinês (Taiwan)
	'zh_HK' => 'Chinese_Hong_Kong',			# Chinês (Hong Kong)
	'zh_CN' => 'Chinese_China',				# Chinês (China)
	'zh_SG' => 'Chinese_Singapore',			# Chinês (Singapura)
	'hr_HR' => 'Croatian_Croatia',			# Croata (Croácia)
	'cs_CZ' => 'Czech_Czech_Republic',		# Checo (República Checa)
	'da_DK' => 'Danish_Denmark',			# Dinamarquês (Dinamarca)
	'pt_BR' => 'Portuguese_Brazil',			# Português (Brasil)
	'nl_NL' => 'Dutch_Netherlands',			# Holandês (Holanda)
	'nl_BE' => 'Dutch_Belgium',				# Holandês (Bélgica)
	'en_GB' => 'English_United Kingdom',	# Inglês (Reino Unido)
	'en_AU' => 'English_Australia',			# Inglês (Austrália)
	'en_BW' => 'English_Botswana',			# Inglês (Botsuana)
	'en_CA' => 'English_Canada',			# Inglês (Canadá)
	'en_DK' => 'English_Denmark',			# Inglês (Dinamarca)
	'en_IE' => 'English_Ireland',			# Inglês (Irlanda)
	'en_NZ' => 'English_New Zealand',		# Inglês (Nova Zelândia)
	'en_PH' => 'English_Philippines',		# Inglês (Filipinas)
	'en_ZA' => 'English_South Africa',		# Inglês (África do Sul)
	'en_US' => 'English_United States',		# Inglês (Estados Unidos)		# English
	'en_ZW' => 'English_Zimbabwe',			# Inglês (Zimbábue)
	'et_EE' => 'Estonian_Estonia',			# Estone (Estônia)
	'fo_FO' => 'Faroese_Faroe Islands',		# Faroês (Ilhas Faroé)
	'fa_IR' => 'Farsi_Iran',				# Persa (Irã)
	'fi_FI' => 'Finnish_Finland',			# Finlandês (Finlândia)
	'fr_FR' => 'French_France',				# Francês (França)
	'fr_BE' => 'French_Belgium',			# Francês (Bélgica)
	'fr_CA' => 'French_Canada',				# Francês (Canadá)
	'fr_LU' => 'French_Luxembourg',			# Francês (Luxemburgo)
	'fr_CH' => 'French_Switzerland',		# Francês (Suíça)
	'gl_ES' => 'Galician_Spain',			# Galego (Espanha)
	'ka_GE' => 'Georgian_Georgia',			# Geórgio (Geórgia)
	'de_DE' => 'German_Germany',			# Alemão (Alemanha)
	'de_AT' => 'German_Austria',			# Alemão (Áustria)
	'de_BE' => 'German_Belgium',			# Alemão (Bélgica)
	'de_LU' => 'German_Luxembourg',			# Alemão (Luxemburgo)
	'de_CH' => 'German_Switzerland',		# Alemão (Suíça)
	'el_GR' => 'Greek_Greece',				# Grego (Grécia)
	'kl_GL' => 'Greenlandic_Greenland',		# Greenlandês (Groenlândia)
	'hu_HU' => 'Hungarian_Hungary',			# Húngaro (Hungria)
	'is_IS' => 'Icelandic_Iceland',			# Islandês (Islândia)
	'id_ID' => 'Indonesian_Indonesia',		# Indonésio (Indonésia)
	'ga_IE' => 'Irish_Ireland',				# Irlandês (Irlanda)
	'it_IT' => 'Italian_Italy',				# Italiano (Itália)
	'it_CH' => 'Italian_Switzerland',		# Italiano (Suíça)
	'ja_JP' => 'Japanese_Japan',			# Japonês (Japão)
	'ks_IN' => 'Kashmiri_India',			# Caxemira (Índia)
	'kw_GB' => 'Cornish_Britain',			# Cornico (Reino Unido)
	'ko_KR' => 'Korean_Korea',				# Coreano (Coreia do Sul)
	'ku_TR' => 'Kurdish_Turkey',			# Curdu (Turquia)
	'lv_LV' => 'Latvian_Latvia',			# Letão (Letônia)
	'lt_LT' => 'Lithuanian_Lithuania',		# Lituano (Lituânia)
	'mk_MK' => 'Macedonian_Macedonia',		# Macedônio (Macedónia)
	'ms_MY' => 'Malay_Malaysia',			# Malaio (Malásia)
	'mt_MT' => 'Maltese_Malta',				# Maltês (Malta)
	'mr_IN' => 'Marathi_India',				# Marathi (Índia)
	'ne_NP' => 'Nepali_Nepal',				# Nepali (Nepal)
	'nb_NO' => 'Norwegian_Norway',			# Norueguês (Noruega)
	'nn_NO' => 'Norwegian_Nynorsk',			# Norueguês (Nova Noruega)
	'pl_PL' => 'Polish_Poland',				# Polonês (Polônia)
	'pt_PT' => 'Portuguese_Portugal',		# Português (Portugal)
	'ro_RO' => 'Romanian_Romania',			# Romeno (Romênia)
	'ru_RU' => 'Russian_Russia',			# Russo (Rússia)
	'ru_UA' => 'Russian_Ukraine',			# Russo (Ucrânia)
	'se_NO' => 'NorthernSami_Norway',		# Sámi do Norte (Noruega)
	'sk_SK' => 'Slovak_Slovakia',			# Eslovaco (Eslováquia)
	'sl_SI' => 'Slovenian_Slovenia',		# Esloveno (Eslovênia)
	'es_ES' => 'Spanish_Spain',				# Espanhol (Espanha)
	'es_AR' => 'Spanish_Argentina',			# Espanhol (Argentina)
	'es_BO' => 'Spanish_Bolivia',			# Espanhol (Bolívia)
	'es_CL' => 'Spanish_Chile',				# Espanhol (Chile)
	'es_CO' => 'Spanish_Colombia',			# Espanhol (Colômbia)
	'es_CR' => 'Spanish_CostaRica',			# Espanhol (Costa Rica)
	'es_DO' => 'Spanish_DominicanRepublic',	# Espanhol (República Dominicana)
	'es_EC' => 'Spanish_Ecuador',			# Espanhol (Equador)
	'es_SV' => 'Spanish_ElSalvador',		# Espanhol (El Salvador)
	'es_GT' => 'Spanish_Guatemala',			# Espanhol (Guatemala)
	'es_HN' => 'Spanish_Honduras',			# Espanhol (Honduras)
	'es_MX' => 'Spanish_Mexico',			# Espanhol (México)
	'es_NI' => 'Spanish_Nicaragua',			# Espanhol (Nicarágua)
	'es_PA' => 'Spanish_Panama',			# Espanhol (Panamá)
	'es_PY' => 'Spanish_Paraguay',			# Espanhol (Paraguai)
	'es_PE' => 'Spanish_Peru',				# Espanhol (Peru)
	'es_PR' => 'Spanish_PuertoRico',		# Espanhol (Porto Rico)
	'es_UY' => 'Spanish_Uruguay',			# Espanhol (Uruguai)
	'es_US' => 'Spanish_UnitedStates',		# Espanhol (Estados Unidos)
	'es_VE' => 'Spanish_Venezuela',			# Espanhol (Venezuela)
	'sw_KE' => 'Swahili_Kenya',				# Suaíli (Quênia)
	'sv_SE' => 'Swedish_Sweden',			# Sueco (Suécia)
	'sv_FI' => 'Swedish_Finland',			# Sueco (Finlândia)
	'tl_PH' => 'Tagalog_Philippines',		# Tagalo (Filipinas)
	'th_TH' => 'Thai_Thailand',				# Tai (Tailândia)
	'tr_TR' => 'Turkish_Turkey',			# Turco (Turquia)
	'uk_UA' => 'Ukrainian_Ukraine',			# Ucraniano (Ucrânia)
	'ur_IN' => 'Urdu_India',				# Urdu (Índia)
	'ur_PK' => 'Urdu_Pakistan',				# Urdu (Paquistão)
	'vi_VN' => 'Vietnamese_Vietnam'			# Vietnamita (Vietnã)
];