name: "Teste"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Teste
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.0
        composer-args: [ "" ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Dependências de cache do PHP
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Instalar dependências
        run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.composer-args }}

      - name: Testes
        run: |
           sudo apt-get update
           sudo apt-get install tzdata locales -y
           sudo locale-gen pt_BR.UTF-8 en_US.UTF-8 es_PY.UTF-8 ru_RU.UTF-8 af_ZA.UTF-8 pt_BR en_US es_PY ru_RU af_ZA
           sudo update-locale
           echo "Todas as linguagens..."
           locale -a
           composer teste