name: "Teste"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Teste
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.0
          - 8.1
        composer-args: [ "" ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Instalar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Dependências de cache do PHP
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-php-${{ matrix.php }}-composer-

      - name: Instalar dependências
        run: composer install --prefer-dist --no-progress --no-suggest ${{ matrix.composer-args }}

      - name: Testes
        run: |
           sudo apt-get update
           sudo apt-get install tzdata locales -y
           sudo locale-gen uk_UA pt_PT.utf8 en_US en_US.utf8 zh_CN.utf8 zh.utf8 es_ES es_ES.utf8 es ar_AE.utf8 ar.utf8 pt_PT de_LU.utf8 fr fr.utf8
           sudo update-locale
           echo "Todas as linguagens..."
           locale -a
           composer teste